title: Francis Hala # your name (or website title) here
logo: "/images/profile.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Detail-oriented professional with a strong background in statistical analysis, machine learning, and data visualization. Posseses Master's Degree in Computer Science from the University of the District of Columbia.
  <br><br>
  Passionate about leveraging data analytics to solve real-world problems and drive strategic decision-making. 
  <br><br>
  <a href="www.linkedin.com/in/francishala/">View My LinkedIn Profile</a> 
  <br><br>
  <a href="https://github.com/haladesigns">View My Github Profile</a> 
  
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
google_analytics: G-JL4S5XYEMZ # your Google Analytics tracking ID here UA-000000-0 
